/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeExperienceRouteImport } from './routes/_home/experience'
import { Route as HomeNotFoundRouteImport } from './routes/_home/not-found'
import { Route as HomeProjectsIndexRouteImport } from './routes/_home/projects/index'
import { Route as HomeProjectsProjectIdRouteImport } from './routes/_home/projects/$projectId'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRoute,
} as any)
const HomeExperienceRoute = HomeExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => HomeRoute,
} as any)
const HomeNotFoundRoute = HomeNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProjectsIndexRoute = HomeProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProjectsProjectIdRoute = HomeProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/experience': typeof HomeExperienceRoute
  '/not-found': typeof HomeNotFoundRoute
  '/projects/$projectId': typeof HomeProjectsProjectIdRoute
  '/projects/': typeof HomeProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/experience': typeof HomeExperienceRoute
  '/not-found': typeof HomeNotFoundRoute
  '/': typeof HomeIndexRoute
  '/projects/$projectId': typeof HomeProjectsProjectIdRoute
  '/projects': typeof HomeProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/_home/about': typeof HomeAboutRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/experience': typeof HomeExperienceRoute
  '/_home/not-found': typeof HomeNotFoundRoute
  '/_home/': typeof HomeIndexRoute
  '/_home/projects/$projectId': typeof HomeProjectsProjectIdRoute
  '/_home/projects/': typeof HomeProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/not-found'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/experience'
    | '/not-found'
    | '/'
    | '/projects/$projectId'
    | '/projects'
  id:
    | '__root__'
    | '/_home'
    | '/_home/about'
    | '/_home/contact'
    | '/_home/experience'
    | '/_home/not-found'
    | '/_home/'
    | '/_home/projects/$projectId'
    | '/_home/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/experience': {
      id: '/_home/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof HomeExperienceRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/not-found': {
      id: '/_home/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof HomeNotFoundRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/projects/': {
      id: '/_home/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof HomeProjectsIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/projects/$projectId': {
      id: '/_home/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof HomeProjectsProjectIdRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeExperienceRoute: typeof HomeExperienceRoute
  HomeNotFoundRoute: typeof HomeNotFoundRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeProjectsProjectIdRoute: typeof HomeProjectsProjectIdRoute
  HomeProjectsIndexRoute: typeof HomeProjectsIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeContactRoute: HomeContactRoute,
  HomeExperienceRoute: HomeExperienceRoute,
  HomeNotFoundRoute: HomeNotFoundRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeProjectsProjectIdRoute: HomeProjectsProjectIdRoute,
  HomeProjectsIndexRoute: HomeProjectsIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
